CREATE DATABASE cognitivo_AI;
GRANT USAGE ON *.* TO root@localhost IDENTIFIED BY 'root'; -- senha é entre aspas mesmo
GRANT ALL PRIVILEGES ON cognitivo_AI.* TO root@localhost;

USE cognitivo_AI;
CREATE TABLE cognitivo_AI.COMP_BOSS
(		
	component_id VARCHAR(255) NOT NULL COMMENT 'CODIGO QUE DIFERENCIA CADA COMPONENTE',
	PRIMARY KEY(component_id), 
	component_type_id VARCHAR(255) NOT NULL COMMENT 'CODIGO QUE INDICA O TIPO DE COMPONENTE',
	type VARCHAR(255) COMMENT 'TIPO DE COMPONENTE',
	connection_type_id VARCHAR(255) COMMENT 'CODIGO QUE INDICA O TIPO DE COONEXAO',
	outside_shape VARCHAR(255) COMMENT 'CODIGO QUE INDICA O TIPO DE ',
	base_type VARCHAR(255) COMMENT 'TIPO DE BASE',
	height_over_tube NUMERIC COMMENT 'ALTURA SOB O TUBO',
	bolt_pattern_long NUMERIC COMMENT 'PADRAO DE COMPRIMENTO',
	bolt_pattern_wide NUMERIC COMMENT 'PADRAO DE LARGURA',
	groove VARCHAR(3) COMMENT 'PROPRIEDADE INTERNA (yes/no)',
	base_diameter NUMERIC COMMENT 'DIAMETRO BASE',
	shoulder_diameter NUMERIC COMMENT 'DIAMETRO MEDIO',
	unique_feature VARCHAR(3) COMMENT 'E PECA UNICA (yes/no)',
	orientation VARCHAR(3) COMMENT 'POSSUI ORIENTACAO (yes/no)',
	weight NUMERIC COMMENT 'INFORMATIVO DE PESO' 
);

USE cognitivo_AI;
CREATE TABLE cognitivo_AI.BILL_OF_MATERIALS
(
	tube_assembly_id VARCHAR(255) NOT NULL COMMENT 'CODIGO QUE DIFERENCIA CADA TUBO',
	PRIMARY KEY(tube_assembly_id),
	component_id_1 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_1 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 1 INDICADO',
	component_id_2 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_2 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 2 INDICADO',
	component_id_3 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_3 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 3 INDICADO',
	component_id_4 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_4 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 4 INDICADO',
	component_id_5 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_5 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 5 INDICADO',
	component_id_6 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_6 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 6 INDICADO',
	component_id_7 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_7 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 7 INDICADO',
	component_id_8 VARCHAR(255) COMMENT 'CODIGO QUE INDICA UM COMPONENTE',
	quantity_8 NUMERIC COMMENT 'QUANTIDADE DO COMPONENTE 8 INDICADO'
);

--FOREIGN KEY (component_id_1) REFERENCES cognitivo_AI.COMP_BOSS(component_id),
--FOREIGN KEY (component_id_2) REFERENCES cognitivo_AI.COMP_BOSS(component_id),
--FOREIGN KEY (component_id_3) REFERENCES cognitivo_AI.COMP_BOSS(component_id),
--FOREIGN KEY (component_id_4) REFERENCES cognitivo_AI.COMP_BOSS(component_id),
--FOREIGN KEY (component_id_5) REFERENCES cognitivo_AI.COMP_BOSS(component_id),
--FOREIGN KEY (component_id_6) REFERENCES cognitivo_AI.COMP_BOSS(component_id),
--FOREIGN KEY (component_id_7) REFERENCES cognitivo_AI.COMP_BOSS(component_id),
--FOREIGN KEY (component_id_8) REFERENCES cognitivo_AI.COMP_BOSS(component_id),

USE cognitivo_AI;
CREATE TABLE cognitivo_AI.PRICE_QUOTE
(		
	tube_assembly_id VARCHAR(255) NOT NULL COMMENT 'CODIGO QUE INDICA UM TUBO',
	FOREIGN KEY (tube_assembly_id) REFERENCES cognitivo_AI.BILL_OF_MATERIALS(tube_assembly_id),
	supplier VARCHAR(255) NOT NULL COMMENT 'CODIGO QUE INDICA UM FORNECEDOR',
	quote_date DATE COMMENT 'DATA DE COTACAO',
	annual_usage NUMERIC COMMENT 'USO ANUAL',
	min_order_quantit NUMERIC COMMENT 'QUANTIDADE MINIMA PARA FORNECIMENTO',
	bracket_pricing VARCHAR(3) COMMENT 'POSSUI SUPORTE (yes/no)',
	quantity NUMERIC COMMENT 'QUANTIDADE DE PRODUTOS',
	cost VARCHAR(255) COMMENT 'CUSTO TOTAL'
);